name: easy_complaint_system
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.0.5
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  fluttertoast: ^8.1.1
  google_fonts: ^4.0.3
  image_picker: ^0.8.7
  permission_handler: ^10.2.0
  path_provider: ^2.0.13
  flutter_image_compress: ^1.1.3
  firebase_storage: ^11.0.15
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  intl: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
